INSERT INTO user(USERNAME, PASSWORD, AUTHORITY, ENABLED)
    VALUES ('user', '0', 'ROLE_USER', true);
INSERT INTO user(USERNAME, PASSWORD, AUTHORITY, ENABLED)
    VALUES ('admin', '1', 'ROLE_ADMIN', true);